import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { compileTokenSources } from "../src/design-system/tokens/compiler";

const sourceFiles = [
  "primitive.tokens.json",
  "semantic.tokens.json",
  "component.tokens.json",
];
const sources = await Promise.all(
  sourceFiles.map(async (filename) => ({
    filename,
    document: JSON.parse(
      await readFile(resolve("tokens", filename), "utf8"),
    ) as Record<string, unknown>,
  })),
);
const bundle = compileTokenSources(sources);

const css = [
  "/* Generated by npm run tokens:build. Do not edit. */",
  ":root {",
  ...bundle.tokens.map(
    (token) => `  ${token.cssVariable}: ${token.cssValue};`,
  ),
  "}",
  "",
].join("\n");
const manifest = [
  "/* Generated by npm run tokens:build. Do not edit. */",
  'import type { TokenBundle } from "../tokens/types";',
  "declare const __MALIK_PORTFOLIO_DESIGN_TOKEN_SOURCE_COMMIT__: string | undefined;",
  "/**",
  " * Production build provenance injected by Vite.",
  ' * "development" is a non-publishable fallback for evaluation outside Vite.',
  " */",
  "export const tokenSourceCommit =",
  '  typeof __MALIK_PORTFOLIO_DESIGN_TOKEN_SOURCE_COMMIT__ === "string"',
  "    ? __MALIK_PORTFOLIO_DESIGN_TOKEN_SOURCE_COMMIT__",
  '    : "development";',
  `export const tokenBundle: TokenBundle = ${JSON.stringify(bundle, null, 2)};`,
  "",
].join("\n");

await mkdir(resolve("src/styles"), { recursive: true });
await mkdir(resolve("src/design-system/generated"), { recursive: true });
await writeFile(resolve("src/styles/tokens.generated.css"), css);
await writeFile(
  resolve("src/design-system/generated/token-manifest.generated.ts"),
  manifest,
);
