import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { compileTokenSources } from "../src/design-system/tokens/compiler";

const sourceFiles = [
  "primitive.tokens.json",
  "semantic.tokens.json",
  "component.tokens.json",
];
const sources = await Promise.all(
  sourceFiles.map(async (filename) => ({
    filename,
    document: JSON.parse(
      await readFile(resolve("tokens", filename), "utf8"),
    ) as Record<string, unknown>,
  })),
);
const bundle = compileTokenSources(sources);
const tokenSourceCommit =
  process.env.VERCEL_GIT_COMMIT_SHA ??
  execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();

const css = [
  "/* Generated by npm run tokens:build. Do not edit. */",
  ":root {",
  ...bundle.tokens.map(
    (token) => `  ${token.cssVariable}: ${token.cssValue};`,
  ),
  "}",
  "",
].join("\n");
const manifest = [
  "/* Generated by npm run tokens:build. Do not edit. */",
  'import type { TokenBundle } from "../tokens/types";',
  `export const tokenSourceCommit = ${JSON.stringify(tokenSourceCommit)};`,
  `export const tokenBundle: TokenBundle = ${JSON.stringify(bundle, null, 2)};`,
  "",
].join("\n");

await mkdir(resolve("src/styles"), { recursive: true });
await mkdir(resolve("src/design-system/generated"), { recursive: true });
await writeFile(resolve("src/styles/tokens.generated.css"), css);
await writeFile(
  resolve("src/design-system/generated/token-manifest.generated.ts"),
  manifest,
);
