import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { compileTokenSources } from "../src/design-system/tokens/compiler";

const sourceFiles = [
  "primitive.tokens.json",
  "semantic.tokens.json",
  "component.tokens.json",
];
const sources = await Promise.all(
  sourceFiles.map(async (filename) => ({
    filename,
    document: JSON.parse(
      await readFile(resolve("tokens", filename), "utf8"),
    ) as Record<string, unknown>,
  })),
);
const bundle = compileTokenSources(sources);

const css = [
  "/* Generated by npm run tokens:build. Do not edit. */",
  ":root {",
  ...bundle.tokens.map(
    (token) => `  ${token.cssVariable}: ${token.cssValue};`,
  ),
  "}",
  "",
].join("\n");
const manifest = [
  "/* Generated by npm run tokens:build. Do not edit. */",
  'import type { TokenBundle } from "../tokens/types";',
  "declare const __MALIK_PORTFOLIO_DESIGN_TOKEN_SOURCE_COMMIT__: string | undefined;",
  "/**",
  " * Production build provenance injected by Vite.",
  ' * "development" is a non-publishable fallback for evaluation outside Vite.',
  " */",
  "export const tokenSourceCommit =",
  '  typeof __MALIK_PORTFOLIO_DESIGN_TOKEN_SOURCE_COMMIT__ === "string"',
  "    ? __MALIK_PORTFOLIO_DESIGN_TOKEN_SOURCE_COMMIT__",
  '    : "development";',
  `export const tokenBundle: TokenBundle = ${JSON.stringify(bundle, null, 2)};`,
  "",
].join("\n");

// Framer cannot read a CSS variable for a transition, so the motion values have
// to exist as JavaScript. Emitting just those twelve here, instead of letting
// src/design-system/system/motion.ts search the whole manifest at module load,
// keeps the 100 KB manifest out of the main bundle: sixteen files import motion,
// and every one of them was dragging the manifest in behind it.
const motionTokens = bundle.tokens.filter(
  (token) => token.path.startsWith("duration.") || token.path.startsWith("ease."),
);
const motion = [
  "/* Generated by npm run tokens:build. Do not edit. */",
  'import type { DtcgCubicBezier, DtcgDuration } from "../tokens/types";',
  "/** Resolved motion token values, for JavaScript-driven animation. */",
  `export const MOTION_TOKENS: Record<string, DtcgDuration | DtcgCubicBezier> = ${JSON.stringify(
    Object.fromEntries(motionTokens.map((token) => [token.path, token.resolvedValue])),
    null,
    2,
  )};`,
  "",
].join("\n");

await mkdir(resolve("src/styles"), { recursive: true });
await mkdir(resolve("src/design-system/generated"), { recursive: true });
await writeFile(resolve("src/styles/tokens.generated.css"), css);
await writeFile(
  resolve("src/design-system/generated/token-manifest.generated.ts"),
  manifest,
);
await writeFile(
  resolve("src/design-system/generated/motion-tokens.generated.ts"),
  motion,
);

// The hash alone, so a fresh draft can be stamped on an ordinary visit without
// loading the manifest it hashes (see preview/PreviewProvider.tsx).
const hash = [
  "/* Generated by npm run tokens:build. Do not edit. */",
  "/** Hash of the token sources; the manifest carries the same value as tokenHash. */",
  `export const TOKEN_HASH = ${JSON.stringify(bundle.tokenHash)};`,
  "",
].join("\n");
await writeFile(
  resolve("src/design-system/generated/token-hash.generated.ts"),
  hash,
);
